---
name: Advent of Code 2023 Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  make-go-days:
    strategy:
      matrix:
        day-no: [1, 4]
    runs-on: ubuntu-latest
    container: golang:1.18
    defaults:
      run:
        working-directory: ./${{ matrix.day-no }}
    steps:
    - uses: actions/checkout@v3
    - name: Test and build day ${{ matrix.day-no }}
      run: |
        make build

  make-notebook-days:
    strategy:
      matrix:
        day-no: [2, 3]
    runs-on: ubuntu-latest
    container: python:3.10
    defaults:
      run:
        shell: bash
        working-directory: ./${{ matrix.day-no }}
    steps:
    - uses: actions/checkout@v3
    # https://python-poetry.org/docs/#ci-recommendations
    - name: Install Poetry
      run: |
        pip install poetry==1.2.0
        poetry --version
    # There are no tests for notebooks, let's try to install it just because we can :)
    - name: Setup day ${{ matrix.day-no }}
      run: |
        make setup

